# Required arguments

input:
    "/rds/project/rds-aFEMMKDjWlo/rarora/mapping/fastq_paths.txt" # two-column file pointing to _1.fastq.gz and _2.fastq.gz files

output: 
    "/rds/project/rds-aFEMMKDjWlo/rarora/mapping/results/uhgv-custom" # output directory to store results

database: 
    bwa_db: "/rds/project/rds-aFEMMKDjWlo/rarora/mapping/databases/uhgv-custom/uhgv-custom.fa" # combined fasta file indexed with BWA
    type: "complete" # contigs or complete
