# Required arguments

input:
    "test/input.tsv" # two-column file pointing to _1.fastq.gz and _2.fastq.gz files

output: 
    "test/output" # output directory to store results

database: 
    bwa_db: "/hps/nobackup2/production/metagenomics/aalmeida/project_latinbiota/databases/proks_euks/uhgg-combined.fa" # combined fasta file indexed with BWA
    type: "contigs" # contigs or complete
